Repository kakao-tech-campus-3rd-step3/Team5_FE, pull requests merged in 2025-09, with the labels that each got.

#6 Feat/issue#2
  src/pages/Archive/Archive.tsx
  src/pages/Archive/hooks/useCanvas.ts
  src/pages/Archive/types/index.ts
  src/pages/Archive/utils/eventHandlers.ts
  src/pages/Archive/utils/makePolygon.ts
Labels: enhancement

#9 Feat/issue#8
  src/pages/Archive/Archive.tsx
  src/pages/Archive/components/Description.tsx
  src/pages/Archive/components/PinnedQuestionList.tsx
  src/pages/Archive/components/QuestionList.tsx
  src/pages/Archive/datas/pinnedDatas.ts
  src/pages/Archive/datas/questionDatas.ts
  src/pages/Archive/hooks/useCanvas.ts
  src/pages/Archive/hooks/usePolygonAnimation.ts
  src/pages/Archive/hooks/useSectionScroll.ts
  src/pages/Archive/utils/makePolygon.ts
Labels: enhancement

#24 feat/20 : 라이벌 페이지 UI 구현
  src/layouts/TempNav.tsx
  src/pages/Feedback/Feedback.tsx
  src/pages/Rival/Rival.tsx
  src/routes/AppRouter.tsx
  src/routes/routePath.ts
Labels: feature

#29 Refactor/28: 피드백 반영 (NavLink 컴포넌트 적용 & 404 등의 라우팅 처리)
  src/layouts/TempNav.tsx
  src/pages/NotFound/NotFound.tsx
  src/routes/AppRouter.tsx
  src/routes/routePath.ts
Labels: refactor

#27 Release/2025-09-12
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .prettierrc
  .vscode/extensions.json
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/Branding/Logo.tsx
  src/components/Branding/Tagline.tsx
  src/components/GNB/GNB.tsx
  src/components/Icons/Icons.tsx
  src/components/Subscribe/BenefitsCard.tsx
  src/components/Subscribe/PricingCard.tsx
  src/layouts/Layout.tsx
  src/layouts/TempNav.tsx
  src/pages/Archive/Archive.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/SelectWork/SelectWork.tsx
  src/pages/Subscribe/Subscribe.tsx
  src/pages/Subscribe/components/BenefitsCard.tsx
  src/pages/Subscribe/components/PricingCard.tsx
  src/routes/AppRouter.tsx
  src/routes/routePath.ts
  src/styles/global.css
  src/styles/index.ts
  src/utils/currency.ts
  tsconfig.json
  vite.config.ts
Labels: release

#36 Feat : 메인 페이지 목데이터 API 연동
  mock/db.json
  src/pages/Home/Home.tsx
Labels: feature

#43 Refactor/42: 메인페이지 컴포넌트 구조 리팩토링
  src/components/Subscribe/BenefitsCard.tsx
  src/components/Subscribe/PricingCard.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/AnswerInput.tsx
  src/pages/Home/components/AnswerSection.tsx
  src/pages/Home/components/AnsweringSection.tsx
  src/pages/Home/components/BeforeAnswerSection.tsx
  src/pages/Home/components/TextInput.tsx
  src/pages/Home/components/VoiceInput.tsx
  src/pages/Home/components/sections/AnsweringSection.tsx
  src/pages/Home/components/sections/BeforeAnswerSection.tsx
  src/pages/Home/components/sections/QuestionCardSection.tsx
Labels: refactor

#41 Feat/40: update pr & issue 템플릿
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#45 Refactor/44: 공통 컴포넌트 & 레이아웃 폴더 구조 리팩토링
  src/components/GNB/GNB.tsx
  src/pages/Home/components/sections/AnsweringSection.tsx
  src/pages/Home/components/sections/BeforeAnswerSection.tsx
  src/pages/Login/Login.tsx
  src/pages/Subscribe/Subscribe.tsx
  src/pages/Subscribe/components/BenefitsCard.tsx
  src/pages/Subscribe/components/PricingCard.tsx
  src/routes/AppRouter.tsx
  src/shared/components/Branding/Tagline.tsx
  src/shared/components/Navigation/Navigation.tsx
  src/shared/components/Navigation/TempNav.tsx
  src/shared/layouts/AuthLayout.tsx
  src/shared/layouts/MainLayout.tsx
  src/shared/types/emotion.d.ts
  src/shared/ui/Logo.tsx
  src/shared/ui/SharedButton.tsx
  src/shared/utils/currency.ts
Labels: refactor

#39 Release/2025-09-19
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  mock/db.json
  package-lock.json
  package.json
  src/components/GNB/GNB.tsx
  src/components/Subscribe/BenefitsCard.tsx
  src/components/Subscribe/PricingCard.tsx
  src/layouts/Layout.tsx
  src/layouts/TempNav.tsx
  src/pages/Archive/Archive.tsx
  src/pages/Archive/assets/lottie/clickIcon.json
  src/pages/Feedback/Feedback.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/AnswerInput.tsx
  src/pages/Home/components/AnswerTypeSelector.tsx
  src/pages/Home/components/TextInput.tsx
  src/pages/Home/components/Timer.tsx
  src/pages/Home/components/VoiceInput.tsx
  src/pages/Home/components/sections/AnsweringSection.tsx
  src/pages/Home/components/sections/BeforeAnswerSection.tsx
  src/pages/Home/components/sections/QuestionCardSection.tsx
  src/pages/Home/hooks/useTimer.ts
  src/pages/Login/Login.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/Rival/Rival.tsx
  src/pages/SelectWork/SelectWork.tsx
  src/pages/Subscribe/Subscribe.tsx
  src/pages/Subscribe/components/BenefitsCard.tsx
  src/pages/Subscribe/components/PricingCard.tsx
  src/routes/AppRouter.tsx
  src/routes/routePath.ts
  src/shared/components/Branding/Tagline.tsx
  src/shared/components/Navigation/Navigation.tsx
  src/shared/components/Navigation/TempNav.tsx
  src/shared/layouts/AuthLayout.tsx
  src/shared/layouts/MainLayout.tsx
  src/shared/types/emotion.d.ts
  src/shared/ui/Logo.tsx
  src/shared/ui/SharedButton.tsx
  src/shared/utils/currency.ts
  src/styles/theme.ts
  src/styles/tokens.ts
Labels: release

#69 Feat/61: 답변 제출 및 피드백 페이지에서 답변 조회 기능 구현
  src/api/feedback.ts
  src/pages/Feedback/Feedback.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/components/AnswerInput.tsx
  src/pages/Home/components/TextInput.tsx
  src/pages/Home/components/sections/AnsweringSection.tsx
Labels: feature
