Repository kakao-tech-campus-3rd-step3/Team5_FE, pull requests merged in 2025-10, with the labels that each got.

#78 Refactor/77: Release/2025-09-26 피드백 반영
  src/pages/Archive/Archive.tsx
  src/pages/Archive/components/PinnedQuestionList.tsx
  src/pages/Archive/components/QuestionList.tsx
  src/pages/Archive/hooks/useAnswer.ts
  src/pages/Feedback/Feedback.tsx
  src/pages/Home/components/AnswerInput.tsx
  src/pages/Home/components/AnswerTypeSelector.tsx
  src/pages/Home/components/Timer.tsx
  src/pages/Home/components/sections/QuestionCardSection.tsx
  src/pages/Home/hooks/useQuestion.ts
  src/pages/Home/hooks/useUser.ts
Labels: refactor

#80 Fix/79: MSW 핸들러 불일치로 인한 API 요청 오류 수정
  src/mock/handlers.ts
Labels: fix

#82 Feat/81: Axios Interceptor 설정 & 반복되는 API 호출 로직 useFetch 훅으로 분리
  src/api/apiClient.ts
  src/pages/Archive/Archive.tsx
  src/pages/Archive/components/PinnedQuestionList.tsx
  src/pages/Archive/components/QuestionList.tsx
  src/pages/Archive/hooks/useAnswer.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/sections/QuestionCardSection.tsx
  src/pages/Home/hooks/useQuestion.ts
  src/pages/Home/hooks/useUser.ts
  src/shared/hooks/useFetch.ts
Labels: feature

#59 Feat/57: 로그인 Flow UI 구현
  KAKAO_LOGIN_SETUP.md
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/config/kakao.ts
  src/pages/JobDetailSelection/JobDetailSelection.tsx
  src/pages/JobSelection/JobSelection.tsx
  src/pages/Login/Login.tsx
  src/pages/PluginInstall/PluginInstall.tsx
Labels: feature
